name: sleepplanner_full_adaptive
description: SleepPlanner with alarm, graphs, and adaptive sleep algorithm.
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  http: ^0.13.6
  audioplayers: ^5.2.1
  table_calendar: ^3.0.9
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
